# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfpro < Formula
  desc ""
  homepage "https://github.com/evners/tfpro"
  version "1.0.0"

  on_macos do
    url "https://github.com/evners/tfpro/releases/download/v1.0.0/tfpro_1.0.0_darwin_all.tar.gz"
    sha256 "e30cea399819038808d212a57cdfc473d9dbd92ae1e7372c94a604e783d05cdf"

    def install
      bin.install "tfpro"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/evners/tfpro/releases/download/v1.0.0/tfpro_1.0.0_linux_arm64.tar.gz"
      sha256 "58bf1f92179c707737384ebde1f9f829d6848f509adaf4bffd1172c9743d7597"

      def install
        bin.install "tfpro"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/evners/tfpro/releases/download/v1.0.0/tfpro_1.0.0_linux_amd64.tar.gz"
      sha256 "e836c328d80dec879817001cf985e34cb761f9f6d25e12d25c7c70f3e3350b8c"

      def install
        bin.install "tfpro"
      end
    end
  end
end
