# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfpro < Formula
  desc ""
  homepage "https://github.com/evners/tfpro"
  version "0.0.6"

  on_macos do
    url "https://github.com/evners/tfpro/releases/download/v0.0.6/tfpro_0.0.6_darwin_all.tar.gz"
    sha256 "db6b6e95594713203e044b5b08c95fb86539656d4b6528cade2a997f64e2efa5"

    def install
      bin.install "tfpro"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/evners/tfpro/releases/download/v0.0.6/tfpro_0.0.6_linux_arm64.tar.gz"
      sha256 "04c92e44539f34e3a395009f420a45bf611f2e773671a5ec4aa4060319da41fa"

      def install
        bin.install "tfpro"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/evners/tfpro/releases/download/v0.0.6/tfpro_0.0.6_linux_amd64.tar.gz"
      sha256 "d2af90d4f9ee7d16dfdde7d4bf6e9912aa6cbe4ac41ace776b3d2091848ae693"

      def install
        bin.install "tfpro"
      end
    end
  end
end
